### ISSUE TITLE
Pressing Enter should Guess if able to.

### ISSUE THREAD

**Issue by jsal13** [jsal13/flag_guesser#17]

**Comment by JaesonLoke** [comment]
var input = document.getElementById("countries");

input.addEventListener("keypress", function(event) {
    // If the user presses the "Enter" key on the keyboard
    if (event.key === "Enter") {
      submitGuess();
    }
  });

**Comment by jsal13** [comment]
Closed with https://github.com/jsal13/flag_guesser/pull/27, nice job!
